### ISSUE TITLE
Register Bower package

### ISSUE THREAD

**Issue by philwareham** [adobe-webplatform/dropcap.js#11]
Although you have a `bower.json` file now, the package has not been registered, so cannot be pulled into projects yet:

http://bower.io/search/?q=dropcap

You can register it using the instructions here:

http://bower.io/docs/creating-packages/#register

**Comment by robneu** [comment]
+1 for registering it.

For anyone who wants to use this before they get around to it, you can pull it in by manually adding it to your bower.json file like so:

`"dropcap": "adobe-webplatform/dropcap.js"`

**Comment by sylvain-galineau** [comment]
Now done; registered as dropcap.js. Thank you.
