### ISSUE TITLE
Dropcap position in paragraph next to floated element

### ISSUE THREAD

**Issue by qodeboy** [adobe-webplatform/dropcap.js#21]
Hello,

This issue is quite rare, and happens only of paragraph with dropcap is located right next to one or more floated elements. 

Particular use-case. Imagine we have an article content blocks, which have some content paraagraphs as well as "inline widgets". Inline widgets are at same level as pargraphs, but floated to the right to look like "sidebar". Design will explain better: http://joxi.ru/VrwYpLphdyOZ2X. 

Here is how it's done:

* Widgets are floated to the left;
* Widgets are "clear:both" so that they don't stack in top of each other;
* Widgets are moved out of the paragraph with negative margin-left;
* Body have padding on the left equal to negative margin-left of the widgets;

This way we can place any number of widgets in any place of article body, along with paragraphs.

But with this setup, this plugin has a positioning issue with a letter. Because widgets are floated and cleared, letter is moved down below last floated widget. Here is a demo: https://jsfiddle.net/psheiman/xu9aadoc/5/

Any ideas on how to fix this?

**Comment by astearns** [comment]
You could add a widget-wrapper div around all the widget divs with .widget-wrapper { float: left; }

**Comment by qodeboy** [comment]
Thanks for a quick turnaround! While your solution works great, this is quite hard to make it live. In our system, those widgets are inserved as tokens (i.e. [widget-foo-bar]) using WYSIWYG. Then, these tokens are replaced with HTML when article is rendered. So having a wrapper around all of them is quite problematic.

I understand this is not related to the plugin itself and is my own headache, but would appreciate any help/suggestions on how to make it without a div wrapper.

**Comment by astearns** [comment]
As far as I know, the wrapper is the only way to get multiple floats to stack up the way you want. The polyfill has to use a float to simulate a dropcap, so we're stuck with the float interactions you're running into. A native initial-letter implementation may be able to do better.

I'll log an issue on the inline layout module to consider this case as we add more detail to https://drafts.csswg.org/css-inline/#initial-letter-floats
